CROSS_COMPILE := /sdk/lichee/brandy-2.0/tools/toolchain/riscv64-linux-x86_64-20200528/bin/riscv64-unknown-linux-gnu-
KDIR := /sdk/lichee/linux-5.4
PWD := $(shell pwd)

obj-m := gpiodriver.o 

gpiodriver-y := sunxi_gpio.o


all:
	make -C $(KDIR) M=$(PWD) CROSS_COMPILE=$(CROSS_COMPILE) ARCH=riscv modules
clean:
	make -C $(KDIR) M=$(PWD) clean